//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_car_record
    {
        public long Id { get; set; }
        public string CarVin { get; set; }
        public string EngineNo { get; set; }
        public string DriveLicenseCarTypeName { get; set; }
        public string DriveLicenseCarTypeValue { get; set; }
        public string LicenseOwner { get; set; }
        public int LicenseOwnerIdType { get; set; }
        public string LicenseOwnerIdTypeValue { get; set; }
        public string LicenseOwnerIdNo { get; set; }
        public int TonCountflag { get; set; }
        public string CarTonCount { get; set; }
        public string CarLotEquQuality { get; set; }
        public Nullable<decimal> VehicleExhaust { get; set; }
        public string FuelType { get; set; }
        public string FuelTypeValue { get; set; }
        public string ProofType { get; set; }
        public string ProofTypeValue { get; set; }
        public string ProofNo { get; set; }
        public Nullable<System.DateTime> ProofTime { get; set; }
        public Nullable<decimal> CarPrice { get; set; }
        public string VehicleYear { get; set; }
        public string VehicleName { get; set; }
        public string ModelCode { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
