//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_drivelicense_cartype
    {
        public int id { get; set; }
        public string type_name { get; set; }
        public string type_value { get; set; }
        public Nullable<int> is_used { get; set; }
        public Nullable<int> company { get; set; }
    }
}
