//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_violationlog
    {
        public long id { get; set; }
        public Nullable<long> b_uid { get; set; }
        public string LicenseNo { get; set; }
        public string lossTime { get; set; }
        public string sanctionDate { get; set; }
        public string lossActionDesc { get; set; }
        public string lossDddress { get; set; }
        public Nullable<decimal> coeff { get; set; }
        public string peccancyid { get; set; }
        public string processingStatus { get; set; }
        public string violationRecordTypeName { get; set; }
        public string acceptagencycode { get; set; }
        public string lossAction { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
