//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_vehicleinfo
    {
        public int Id { get; set; }
        public string brand_id { get; set; }
        public string parent_id { get; set; }
        public string vehicle_id { get; set; }
        public string brand_name { get; set; }
        public string standard_name { get; set; }
        public string family_name { get; set; }
        public string engine_desc { get; set; }
        public string gearbox_name { get; set; }
        public string parent_veh_name { get; set; }
        public string vehicle_fgw_code { get; set; }
        public Nullable<double> seat { get; set; }
        public Nullable<double> seat_flag { get; set; }
        public Nullable<double> import_flag { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> taxprice { get; set; }
        public string market_date { get; set; }
        public string vin_code { get; set; }
        public string vehicle_type { get; set; }
        public string tom_number { get; set; }
        public string whole_weight { get; set; }
        public string brand_model { get; set; }
        public string engine_no { get; set; }
        public string car_vin { get; set; }
        public string year { get; set; }
    }
}
