//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiHuManBu.ExternalInterfaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bx_ywxdetail
    {
        public long id { get; set; }
        public Nullable<long> b_uid { get; set; }
        public Nullable<int> source { get; set; }
        public string classid { get; set; }
        public string classname { get; set; }
        public string brandcode { get; set; }
        public string brandname { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    }
}
